export type DealStage =
  | 'nowy-lead'
  | 'dm-wyslany'
  | 'odpowiedz'
  | 'rozmowa-umowiona'
  | 'diagnoza'
  | 'oferta'
  | 'negocjacje'
  | 'wygrana'
  | 'przegrana'
  | 'nie-teraz'

export type AiScore = 'hot' | 'warm' | 'cold'

export interface DealNote {
  date: string
  author: string
  content: string
}

export interface Deal {
  id: string
  company: string
  contactName: string
  position: string
  value: number
  stage: DealStage
  aiScore: AiScore
  aiScoreNum: number
  lastContact: string
  email: string
  phone: string
  segment: string
  notes: DealNote[]
  nextStep: string
  projectScope: string
  lostReason?: string
}

export const STAGE_CONFIG: Record<DealStage, { label: string; color: string; bg: string }> = {
  'nowy-lead':          { label: 'Nowy lead',           color: '#94a3b8', bg: 'rgba(148,163,184,0.1)' },
  'dm-wyslany':         { label: 'DM wysłany',          color: '#60a5fa', bg: 'rgba(96,165,250,0.1)' },
  'odpowiedz':          { label: 'Odpowiedź',           color: '#a78bfa', bg: 'rgba(167,139,250,0.1)' },
  'rozmowa-umowiona':   { label: 'Rozmowa umówiona',    color: '#f59e0b', bg: 'rgba(245,158,11,0.1)' },
  'diagnoza':           { label: 'Diagnoza zrobiona',   color: '#fb923c', bg: 'rgba(251,146,60,0.1)' },
  'oferta':             { label: 'Oferta prezentowana', color: '#6366f1', bg: 'rgba(99,102,241,0.1)' },
  'negocjacje':         { label: 'Negocjacje',          color: '#ec4899', bg: 'rgba(236,72,153,0.1)' },
  'wygrana':            { label: 'WYGRANA',             color: '#22c55e', bg: 'rgba(34,197,94,0.12)' },
  'przegrana':          { label: 'PRZEGRANA',           color: '#ef4444', bg: 'rgba(239,68,68,0.1)' },
  'nie-teraz':          { label: 'NIE TERAZ',           color: '#64748b', bg: 'rgba(100,116,139,0.1)' },
}

export const MOCK_DEALS: Deal[] = [
  // NOWY LEAD (8)
  {
    id: 'd1',
    company: 'Pulse Marketing',
    contactName: 'Katarzyna Witek',
    position: 'CEO',
    value: 9600,
    stage: 'nowy-lead',
    aiScore: 'warm',
    aiScoreNum: 68,
    lastContact: '2026-04-07',
    email: 'k.witek@pulsemarketing.pl',
    phone: '+48 601 111 001',
    segment: 'agencja',
    nextStep: 'Wysłać spersonalizowany DM z case study',
    projectScope: 'Wdrożenie systemu CRM + automatyzacja outreach',
    notes: [{ date: '2026-04-07', author: 'Anna K.', content: 'Znaleziona przez LinkedIn Search. Profil pasuje do ICP.' }],
  },
  {
    id: 'd2',
    company: 'Digital Nest',
    contactName: 'Piotr Malinowski',
    position: 'Head of Growth',
    value: 14400,
    stage: 'nowy-lead',
    aiScore: 'hot',
    aiScoreNum: 82,
    lastContact: '2026-04-06',
    email: 'p.malinowski@digitalnest.pl',
    phone: '+48 601 111 002',
    segment: 'agencja',
    nextStep: 'Zaproszenie LinkedIn + DM inicjalny',
    projectScope: 'System AI scoring + generator treści',
    notes: [{ date: '2026-04-06', author: 'Anna K.', content: 'Widać że mają problem z zarządzaniem leadami – 3 posty o tym w ostatnim miesiącu.' }],
  },
  {
    id: 'd3',
    company: 'AdFlow Agency',
    contactName: 'Monika Lis',
    position: 'Founder',
    value: 11200,
    stage: 'nowy-lead',
    aiScore: 'warm',
    aiScoreNum: 61,
    lastContact: '2026-04-05',
    email: 'm.lis@adflow.pl',
    phone: '+48 601 111 003',
    segment: 'agencja',
    nextStep: 'Pierwsze wyjście przez IG',
    projectScope: 'Kalendarz contentu + Portal klienta',
    notes: [],
  },
  {
    id: 'd4',
    company: 'Hype Studio',
    contactName: 'Damian Kowalski',
    position: 'Owner',
    value: 8000,
    stage: 'nowy-lead',
    aiScore: 'cold',
    aiScoreNum: 41,
    lastContact: '2026-04-03',
    email: 'd.kowalski@hypestudio.pl',
    phone: '+48 601 111 004',
    segment: 'agencja',
    nextStep: 'Zrezygnować lub spróbować za 2 tyg.',
    projectScope: 'Podstawowy CRM',
    notes: [],
  },
  {
    id: 'd5',
    company: 'Brandero',
    contactName: 'Zofia Nowak',
    position: 'Marketing Director',
    value: 16800,
    stage: 'nowy-lead',
    aiScore: 'hot',
    aiScoreNum: 88,
    lastContact: '2026-04-07',
    email: 'z.nowak@brandero.pl',
    phone: '+48 601 111 005',
    segment: 'agencja',
    nextStep: 'Zaproszenie + customowy DM nawiązujący do ich kampanii',
    projectScope: 'Pełne wdrożenie AgencyOS',
    notes: [{ date: '2026-04-07', author: 'Anna K.', content: 'Duża agencja, budżet potwierdzony przez sieć kontaktów.' }],
  },
  {
    id: 'd6',
    company: 'Konwersja.pl',
    contactName: 'Artur Ząbek',
    position: 'CEO',
    value: 12000,
    stage: 'nowy-lead',
    aiScore: 'warm',
    aiScoreNum: 74,
    lastContact: '2026-04-04',
    email: 'a.zabek@konwersja.pl',
    phone: '+48 601 111 006',
    segment: 'agencja',
    nextStep: 'DM przez LinkedIn z social proof',
    projectScope: 'CRM + Analityka sprzedażowa',
    notes: [],
  },
  {
    id: 'd7',
    company: 'MindSpark Creative',
    contactName: 'Weronika Jabłońska',
    position: 'Founder',
    value: 9800,
    stage: 'nowy-lead',
    aiScore: 'warm',
    aiScoreNum: 66,
    lastContact: '2026-04-05',
    email: 'w.jablonska@mindspark.pl',
    phone: '+48 601 111 007',
    segment: 'agencja',
    nextStep: 'Zimne wyjście przez e-mail',
    projectScope: 'Generator treści AI + Kalendarz',
    notes: [],
  },
  {
    id: 'd8',
    company: 'Visible Agency',
    contactName: 'Tomasz Wróbel',
    position: 'CEO',
    value: 13600,
    stage: 'nowy-lead',
    aiScore: 'hot',
    aiScoreNum: 79,
    lastContact: '2026-04-06',
    email: 't.wrobel@visible.pl',
    phone: '+48 601 111 008',
    segment: 'agencja',
    nextStep: 'DM nawiązujący do ich bloga',
    projectScope: 'Wdrożenie systemu + szkolenie zespołu',
    notes: [],
  },

  // DM WYSŁANY (6)
  {
    id: 'd9',
    company: 'Social Sharks',
    contactName: 'Natalia Kowalczyk',
    position: 'Founder',
    value: 14400,
    stage: 'dm-wyslany',
    aiScore: 'hot',
    aiScoreNum: 85,
    lastContact: '2026-04-06',
    email: 'natalia@socialsharks.pl',
    phone: '+48 601 112 001',
    segment: 'agencja',
    nextStep: 'Follow-up za 2 dni jeśli brak odpowiedzi',
    projectScope: 'Pełne wdrożenie CRM + outreach',
    notes: [{ date: '2026-04-06', author: 'Anna K.', content: 'DM inicjalny wysłany. Bardzo aktywna na LinkedIn.' }],
  },
  {
    id: 'd10',
    company: 'ClickBoost Agency',
    contactName: 'Marek Zaremba',
    position: 'CEO',
    value: 18000,
    stage: 'dm-wyslany',
    aiScore: 'hot',
    aiScoreNum: 91,
    lastContact: '2026-04-05',
    email: 'm.zaremba@clickboost.pl',
    phone: '+48 601 112 002',
    segment: 'agencja',
    nextStep: 'Follow-up z case study o ROI',
    projectScope: 'Enterprise – pełny system + integracje',
    notes: [{ date: '2026-04-05', author: 'Anna K.', content: 'Zaproszenie zaakceptowane w ciągu godziny. Wysoki sygnał zainteresowania.' }],
  },
  {
    id: 'd11',
    company: 'ContentFactory',
    contactName: 'Agata Wierzbicka',
    position: 'CEO',
    value: 10800,
    stage: 'dm-wyslany',
    aiScore: 'warm',
    aiScoreNum: 73,
    lastContact: '2026-04-04',
    email: 'agata@contentfactory.pl',
    phone: '+48 601 112 003',
    segment: 'agencja',
    nextStep: 'Follow-up po weekendzie',
    projectScope: 'Generator treści AI + Kalendarz contentu',
    notes: [],
  },
  {
    id: 'd12',
    company: 'MediaHouse Warsaw',
    contactName: 'Robert Kowalczewski',
    position: 'Head of Sales',
    value: 22800,
    stage: 'dm-wyslany',
    aiScore: 'hot',
    aiScoreNum: 87,
    lastContact: '2026-04-07',
    email: 'r.kowalczewski@mediahouse.pl',
    phone: '+48 601 112 004',
    segment: 'agencja',
    nextStep: 'Czekam na odpowiedź – wiadomość czytana 2x',
    projectScope: 'Wdrożenie systemu dla całego zespołu (8 os.)',
    notes: [{ date: '2026-04-07', author: 'Anna K.', content: 'DM z personalizowanym case study dla agencji media. Czytana 2 razy.' }],
  },
  {
    id: 'd13',
    company: 'Kreacja Plus',
    contactName: 'Ewa Nowacka',
    position: 'Founder',
    value: 8400,
    stage: 'dm-wyslany',
    aiScore: 'warm',
    aiScoreNum: 62,
    lastContact: '2026-04-03',
    email: 'ewa@kreacjaplus.pl',
    phone: '+48 601 112 005',
    segment: 'agencja',
    nextStep: 'Follow-up #2 – inna forma (wideo?)',
    projectScope: 'CRM podstawowy + onboarding klientów',
    notes: [],
  },
  {
    id: 'd14',
    company: 'WaveMedia',
    contactName: 'Szymon Duda',
    position: 'CEO',
    value: 15600,
    stage: 'dm-wyslany',
    aiScore: 'warm',
    aiScoreNum: 71,
    lastContact: '2026-04-06',
    email: 's.duda@wavemedia.pl',
    phone: '+48 601 112 006',
    segment: 'agencja',
    nextStep: 'Jeden follow-up, potem cold',
    projectScope: 'System AI scoring + automatyzacja',
    notes: [],
  },

  // ODPOWIEDŹ (5)
  {
    id: 'd15',
    company: 'Twórcza Agencja',
    contactName: 'Beata Lewandowska',
    position: 'Owner',
    value: 11600,
    stage: 'odpowiedz',
    aiScore: 'warm',
    aiScoreNum: 77,
    lastContact: '2026-04-07',
    email: 'beata@tworczaagencja.pl',
    phone: '+48 601 113 001',
    segment: 'agencja',
    nextStep: 'Zaprosić na rozmowę 30 min',
    projectScope: 'CRM + Generator Treści',
    notes: [{ date: '2026-04-07', author: 'Anna K.', content: 'Odpowiedziała: "Brzmi interesująco, co dokładnie oferujecie?" – dobry sygnał.' }],
  },
  {
    id: 'd16',
    company: 'Viral Growth',
    contactName: 'Kamil Nowacki',
    position: 'Founder',
    value: 13200,
    stage: 'odpowiedz',
    aiScore: 'hot',
    aiScoreNum: 84,
    lastContact: '2026-04-06',
    email: 'kamil@viralgrowth.pl',
    phone: '+48 601 113 002',
    segment: 'agencja',
    nextStep: 'Wysłać szczegóły systemu + umówić demo',
    projectScope: 'Pełne wdrożenie + szkolenie',
    notes: [{ date: '2026-04-06', author: 'Anna K.', content: 'Zainteresowany, prosi o więcej info o funkcjach AI.' }],
  },
  {
    id: 'd17',
    company: 'Impact Digital',
    contactName: 'Michał Szymański',
    position: 'CEO',
    value: 19200,
    stage: 'odpowiedz',
    aiScore: 'hot',
    aiScoreNum: 89,
    lastContact: '2026-04-05',
    email: 'm.szymanski@impactdigital.pl',
    phone: '+48 601 113 003',
    segment: 'agencja',
    nextStep: 'Zaproponować rozmowę w tym tygodniu',
    projectScope: 'Enterprise wdrożenie systemu',
    notes: [{ date: '2026-04-05', author: 'Anna K.', content: 'Bardzo ciepła odpowiedź. Podał że mają 5-osobowy sales team bez systemu CRM.' }],
  },
  {
    id: 'd18',
    company: 'Flux Creative',
    contactName: 'Joanna Białkowska',
    position: 'Head of Growth',
    value: 9400,
    stage: 'odpowiedz',
    aiScore: 'warm',
    aiScoreNum: 69,
    lastContact: '2026-04-04',
    email: 'j.bialkowska@fluxcreative.pl',
    phone: '+48 601 113 004',
    segment: 'agencja',
    nextStep: 'Odpowiedzieć na pytania dot. integracji',
    projectScope: 'Moduł outreach + kalendarz contentu',
    notes: [],
  },
  {
    id: 'd19',
    company: 'Prism Agency',
    contactName: 'Łukasz Woźniak',
    position: 'CEO',
    value: 16000,
    stage: 'odpowiedz',
    aiScore: 'warm',
    aiScoreNum: 75,
    lastContact: '2026-04-03',
    email: 'lukasz@prismagency.pl',
    phone: '+48 601 113 005',
    segment: 'agencja',
    nextStep: 'Wysłać case study + zaproponować call',
    projectScope: 'Wdrożenie CRM dla agencji 10-osobowej',
    notes: [],
  },

  // ROZMOWA UMÓWIONA (4)
  {
    id: 'd20',
    company: 'Nexus Media',
    contactName: 'Aleksandra Pawlak',
    position: 'CEO',
    value: 21600,
    stage: 'rozmowa-umowiona',
    aiScore: 'hot',
    aiScoreNum: 92,
    lastContact: '2026-04-07',
    email: 'a.pawlak@nexusmedia.pl',
    phone: '+48 601 114 001',
    segment: 'agencja',
    nextStep: 'Rozmowa jutro 10:00 – przygotować deck',
    projectScope: 'Enterprise – pełny system dla agencji 15 os.',
    notes: [
      { date: '2026-04-05', author: 'Anna K.', content: 'Umówiłam call na 9 kwietnia 10:00.' },
      { date: '2026-04-07', author: 'Anna K.', content: 'Potwierdziła rozmowę. Bardzo zainteresowana modułem AI scoring.' },
    ],
  },
  {
    id: 'd21',
    company: 'Echo Digital',
    contactName: 'Bartosz Malinowski',
    position: 'Founder',
    value: 14400,
    stage: 'rozmowa-umowiona',
    aiScore: 'hot',
    aiScoreNum: 83,
    lastContact: '2026-04-06',
    email: 'bartosz@echodigital.pl',
    phone: '+48 601 114 002',
    segment: 'agencja',
    nextStep: 'Rozmowa 10 kwietnia 14:00',
    projectScope: 'CRM + outreach queue',
    notes: [{ date: '2026-04-06', author: 'Anna K.', content: 'Rozmowa umówiona. Podał że mają problem głównie z follow-upami.' }],
  },
  {
    id: 'd22',
    company: 'Bold Creative',
    contactName: 'Marta Kowalska',
    position: 'Owner',
    value: 12000,
    stage: 'rozmowa-umowiona',
    aiScore: 'warm',
    aiScoreNum: 78,
    lastContact: '2026-04-05',
    email: 'm.kowalska@boldcreative.pl',
    phone: '+48 601 114 003',
    segment: 'agencja',
    nextStep: 'Call 11 kwietnia',
    projectScope: 'Moduły: CRM, Generator Treści, Finanse',
    notes: [],
  },
  {
    id: 'd23',
    company: 'Spark Agency',
    contactName: 'Piotr Kowalski',
    position: 'CEO',
    value: 9800,
    stage: 'rozmowa-umowiona',
    aiScore: 'warm',
    aiScoreNum: 72,
    lastContact: '2026-04-04',
    email: 'piotr@sparkagency.pl',
    phone: '+48 601 114 004',
    segment: 'agencja',
    nextStep: 'Call 12 kwietnia',
    projectScope: 'System CRM – agencja 5-osobowa',
    notes: [],
  },

  // DIAGNOZA (3)
  {
    id: 'd24',
    company: 'Atom Creative',
    contactName: 'Karolina Wróbel',
    position: 'Head of Sales',
    value: 24000,
    stage: 'diagnoza',
    aiScore: 'hot',
    aiScoreNum: 94,
    lastContact: '2026-04-07',
    email: 'k.wrobel@atomcreative.pl',
    phone: '+48 601 115 001',
    segment: 'agencja',
    nextStep: 'Przygotować ofertę na podstawie notatek z diagnozy',
    projectScope: 'Pełne wdrożenie – 12 modułów, 10 os.',
    notes: [
      { date: '2026-04-03', author: 'Anna K.', content: 'Diagnoza 60 min. Główny ból: brak struktury pipeline + generator contentu.' },
      { date: '2026-04-07', author: 'Anna K.', content: 'Przesłali mi dostęp do ich obecnego narzędzia – widzę gdzie tracimy. Przygotowuję ofertę.' },
    ],
  },
  {
    id: 'd25',
    company: 'Pixel & Co',
    contactName: 'Rafał Malinowski',
    position: 'CEO',
    value: 16800,
    stage: 'diagnoza',
    aiScore: 'hot',
    aiScoreNum: 87,
    lastContact: '2026-04-06',
    email: 'rafal@pixelco.pl',
    phone: '+48 601 115 002',
    segment: 'agencja',
    nextStep: 'Dokończyć analizę potrzeb, wysłać ofertę',
    projectScope: 'CRM + finanse + analityka',
    notes: [{ date: '2026-04-06', author: 'Anna K.', content: 'Dobra rozmowa. CEO chce wszystko zrozumieć przed decyzją – to dobry znak.' }],
  },
  {
    id: 'd26',
    company: 'Craft Media',
    contactName: 'Iga Nowak',
    position: 'Founder',
    value: 13200,
    stage: 'diagnoza',
    aiScore: 'warm',
    aiScoreNum: 76,
    lastContact: '2026-04-05',
    email: 'iga@craftmedia.pl',
    phone: '+48 601 115 003',
    segment: 'agencja',
    nextStep: 'Wycena na miarę – wysyłam jutro',
    projectScope: 'Generator treści AI + portal klienta',
    notes: [],
  },

  // OFERTA (3)
  {
    id: 'd27',
    company: 'Momentum Agency',
    contactName: 'Tomasz Grabowski',
    position: 'CEO',
    value: 19200,
    stage: 'oferta',
    aiScore: 'hot',
    aiScoreNum: 90,
    lastContact: '2026-04-07',
    email: 't.grabowski@momentumagency.pl',
    phone: '+48 601 116 001',
    segment: 'agencja',
    nextStep: 'Follow-up jutro po 48h od wysłania oferty',
    projectScope: 'Enterprise – wdrożenie + onboarding 3 tygodnie',
    notes: [
      { date: '2026-04-04', author: 'Anna K.', content: 'Oferta wysłana przez portal. Otwarta 4 razy.' },
      { date: '2026-04-07', author: 'Anna K.', content: 'Pyta o dodatkową integrację z HubSpot.' },
    ],
  },
  {
    id: 'd28',
    company: 'Rise Digital',
    contactName: 'Anna Lewandowska',
    position: 'Owner',
    value: 14400,
    stage: 'oferta',
    aiScore: 'hot',
    aiScoreNum: 86,
    lastContact: '2026-04-06',
    email: 'anna@risedigital.pl',
    phone: '+48 601 116 002',
    segment: 'agencja',
    nextStep: 'Czekam na decyzję do piątku',
    projectScope: 'CRM + outreach + generator treści',
    notes: [{ date: '2026-04-06', author: 'Anna K.', content: 'Oferta otwarta 6 razy. Bardzo duże zainteresowanie.' }],
  },
  {
    id: 'd29',
    company: 'Steer Agency',
    contactName: 'Jakub Nowakowski',
    position: 'Head of Growth',
    value: 11600,
    stage: 'oferta',
    aiScore: 'warm',
    aiScoreNum: 74,
    lastContact: '2026-04-05',
    email: 'j.nowakowski@steer.pl',
    phone: '+48 601 116 003',
    segment: 'agencja',
    nextStep: 'Odpowiedzieć na pytania i poprosić o decyzję',
    projectScope: 'System dla agencji 6-osobowej',
    notes: [],
  },

  // NEGOCJACJE (2)
  {
    id: 'd30',
    company: 'MediaHouse Warsaw',
    contactName: 'Robert Kowalczewski',
    position: 'Head of Sales',
    value: 22800,
    stage: 'negocjacje',
    aiScore: 'hot',
    aiScoreNum: 95,
    lastContact: '2026-04-07',
    email: 'r.kowalczewski@mediahouse.pl',
    phone: '+48 601 117 001',
    segment: 'agencja',
    nextStep: 'Finalizacja warunków umowy – call jutro',
    projectScope: 'Pełne wdrożenie dla 8-osobowego zespołu',
    notes: [
      { date: '2026-04-01', author: 'Anna K.', content: 'Chcą rabat 10% przy płatności z góry za rok.' },
      { date: '2026-04-05', author: 'Anna K.', content: 'Wstępnie zgodziłam się na 7% rabatu. Czekam na potwierdzenie zarządu.' },
      { date: '2026-04-07', author: 'Anna K.', content: 'Zarząd zatwierdził. Finalizujemy umowę.' },
    ],
  },
  {
    id: 'd31',
    company: 'Grow Digital',
    contactName: 'Sylwia Krawczyk',
    position: 'CEO',
    value: 16800,
    stage: 'negocjacje',
    aiScore: 'hot',
    aiScoreNum: 88,
    lastContact: '2026-04-06',
    email: 's.krawczyk@growdigital.pl',
    phone: '+48 601 117 002',
    segment: 'agencja',
    nextStep: 'Ustalić harmonogram wdrożenia',
    projectScope: 'CRM + analityka + finanse',
    notes: [{ date: '2026-04-06', author: 'Anna K.', content: 'Negocjują rozłożenie płatności na 3 transze.' }],
  },

  // WYGRANA (4)
  {
    id: 'd32',
    company: 'Kreacja Premium',
    contactName: 'Michał Adamski',
    position: 'CEO',
    value: 18000,
    stage: 'wygrana',
    aiScore: 'hot',
    aiScoreNum: 96,
    lastContact: '2026-03-28',
    email: 'm.adamski@kreacjapremium.pl',
    phone: '+48 601 118 001',
    segment: 'agencja',
    nextStep: 'Onboarding – tydzień 1 zakończony',
    projectScope: 'Pełne wdrożenie systemu AgencyOS',
    notes: [{ date: '2026-03-28', author: 'Anna K.', content: 'Umowa podpisana! Wpłynęła zaliczka 3600 PLN.' }],
  },
  {
    id: 'd33',
    company: 'TopLine Agency',
    contactName: 'Karolina Dąbrowska',
    position: 'Founder',
    value: 12000,
    stage: 'wygrana',
    aiScore: 'hot',
    aiScoreNum: 91,
    lastContact: '2026-04-02',
    email: 'k.dabrowska@topline.pl',
    phone: '+48 601 118 002',
    segment: 'agencja',
    nextStep: 'Trwa onboarding tydzień 2',
    projectScope: 'CRM + generator treści + portal klienta',
    notes: [{ date: '2026-04-02', author: 'Anna K.', content: 'Świetny onboarding – zespół bardzo aktywny w systemie.' }],
  },
  {
    id: 'd34',
    company: 'Sigma Marketing',
    contactName: 'Paweł Zielański',
    position: 'CEO',
    value: 14400,
    stage: 'wygrana',
    aiScore: 'hot',
    aiScoreNum: 89,
    lastContact: '2026-03-15',
    email: 'pawel@sigmamarketing.pl',
    phone: '+48 601 118 003',
    segment: 'agencja',
    nextStep: 'Klient aktywny – miesięczny abonament',
    projectScope: 'System CRM + abonament wsparcia',
    notes: [],
  },
  {
    id: 'd35',
    company: 'Nova Agency',
    contactName: 'Izabela Krawczyk',
    position: 'Owner',
    value: 9600,
    stage: 'wygrana',
    aiScore: 'warm',
    aiScoreNum: 81,
    lastContact: '2026-03-20',
    email: 'izabela@novaagency.pl',
    phone: '+48 601 118 004',
    segment: 'agencja',
    nextStep: 'Klient zadowolony – pytanie o rozszerzenie',
    projectScope: 'Podstawowy pakiet CRM',
    notes: [],
  },

  // PRZEGRANA (2)
  {
    id: 'd36',
    company: 'Legacy Media',
    contactName: 'Andrzej Zając',
    position: 'CEO',
    value: 16800,
    stage: 'przegrana',
    aiScore: 'warm',
    aiScoreNum: 70,
    lastContact: '2026-03-10',
    email: 'a.zajac@legacymedia.pl',
    phone: '+48 601 119 001',
    segment: 'agencja',
    nextStep: '',
    projectScope: 'Pełne wdrożenie',
    lostReason: 'Za drogo – wybrali tańsze rozwiązanie',
    notes: [{ date: '2026-03-10', author: 'Anna K.', content: 'Wybrali konkurencję – niższa cena. Możliwy powrót za 6 mies.' }],
  },
  {
    id: 'd37',
    company: 'Flat Agency',
    contactName: 'Dominika Nowak',
    position: 'Founder',
    value: 9600,
    stage: 'przegrana',
    aiScore: 'cold',
    aiScoreNum: 42,
    lastContact: '2026-03-05',
    email: 'd.nowak@flatagency.pl',
    phone: '+48 601 119 002',
    segment: 'agencja',
    nextStep: '',
    projectScope: 'CRM podstawowy',
    lostReason: 'Nie teraz – zamrożony budżet Q1',
    notes: [],
  },

  // NIE TERAZ (3)
  {
    id: 'd38',
    company: 'Vibe Creative',
    contactName: 'Paulina Mazur',
    position: 'Owner',
    value: 12000,
    stage: 'nie-teraz',
    aiScore: 'warm',
    aiScoreNum: 65,
    lastContact: '2026-02-20',
    email: 'paulina@vibecreative.pl',
    phone: '+48 601 120 001',
    segment: 'agencja',
    nextStep: 'Przypomnienie 1 maja',
    projectScope: 'Generator treści + CRM',
    notes: [{ date: '2026-02-20', author: 'Anna K.', content: 'Mają projekt do maja. Wrócimy w Q2.' }],
  },
  {
    id: 'd39',
    company: 'Pulse Studio',
    contactName: 'Grzegorz Witkowski',
    position: 'CEO',
    value: 8400,
    stage: 'nie-teraz',
    aiScore: 'cold',
    aiScoreNum: 48,
    lastContact: '2026-02-10',
    email: 'grzegorz@pulsestudio.pl',
    phone: '+48 601 120 002',
    segment: 'agencja',
    nextStep: 'Przypomnienie czerwiec',
    projectScope: 'Podstawowy pakiet',
    notes: [],
  },
  {
    id: 'd40',
    company: 'ClearMind Marketing',
    contactName: 'Monika Kamińska',
    position: 'Head of Growth',
    value: 14400,
    stage: 'nie-teraz',
    aiScore: 'warm',
    aiScoreNum: 68,
    lastContact: '2026-03-01',
    email: 'm.kaminska@clearmind.pl',
    phone: '+48 601 120 003',
    segment: 'agencja',
    nextStep: 'Przypomnienie 15 maja',
    projectScope: 'CRM + analityka',
    notes: [{ date: '2026-03-01', author: 'Anna K.', content: 'Właśnie zmienili CRM – chcą dać mu szansę przez 3 miesiące.' }],
  },
]
