export type AiScore = 'hot' | 'warm' | 'cold'

export interface Lead {
  id: string
  firstName: string
  lastName: string
  company: string
  position: string
  email: string
  phone: string
  city: string
  segment: string
  aiScore: number
  aiLabel: AiScore
  status: 'nowy' | 'kontakt' | 'zainteresowany' | 'pipeline' | 'nieaktywny'
  lastContact: string
  problem: string
  icebreaker: string
  website?: string
  linkedin?: string
  notes?: string
  outreachHistory: {
    date: string
    type: string
    content: string
  }[]
}

export const MOCK_LEADS: Lead[] = [
  {
    id: 'l1',
    firstName: 'Marta',
    lastName: 'Wiśniewska',
    company: 'Glow Clinic',
    position: 'Owner',
    email: 'marta.w@glowclinic.pl',
    phone: '+48 601 234 567',
    city: 'Warszawa',
    segment: 'beauty',
    aiScore: 91,
    aiLabel: 'hot',
    status: 'zainteresowany',
    lastContact: '2026-04-06',
    problem: 'Brak systemu do śledzenia leadów z Meta Ads – tracimy potencjalnych klientów',
    icebreaker: 'Widziałam że prowadzicie kampanie dla klinik estetycznych – mam coś co może was bardzo zainteresować',
    website: 'glowclinic.pl',
    linkedin: 'linkedin.com/in/martaw',
    notes: 'Bardzo zainteresowana automatyzacją follow-upów. Budżet ok. 2k/mc.',
    outreachHistory: [
      { date: '2026-03-28', type: 'LinkedIn DM', content: 'Pierwsze zaproszenie do sieci – zaakceptowane.' },
      { date: '2026-04-01', type: 'DM #1', content: 'Wiadomość o systemie – odpowiedziała po 2h.' },
      { date: '2026-04-06', type: 'DM #2', content: 'Follow-up z case study. Prosi o demo.' },
    ],
  },
  {
    id: 'l2',
    firstName: 'Kamil',
    lastName: 'Nowak',
    company: 'FitZone Kraków',
    position: 'Founder',
    email: 'kamil@fitzone.pl',
    phone: '+48 602 345 678',
    city: 'Kraków',
    segment: 'fitness',
    aiScore: 84,
    aiLabel: 'hot',
    status: 'zainteresowany',
    lastContact: '2026-04-05',
    problem: 'Ręczne zarządzanie zapisami na treningi i brak retencji klientów',
    icebreaker: 'Widziałem że macie 3 lokalizacje – przy takim rozmiarze automatyzacja to oszczędność 10h/tydzień',
    website: 'fitzone.pl',
    outreachHistory: [
      { date: '2026-03-30', type: 'LinkedIn', content: 'Zaproszenie zaakceptowane.' },
      { date: '2026-04-05', type: 'DM #1', content: 'Wysłałem ofertę wstępną. Czeka na rozmowę.' },
    ],
  },
  {
    id: 'l3',
    firstName: 'Anna',
    lastName: 'Kowalczyk',
    company: 'Dentica Pro',
    position: 'CEO',
    email: 'a.kowalczyk@dentica.pl',
    phone: '+48 603 456 789',
    city: 'Wrocław',
    segment: 'medyczne',
    aiScore: 78,
    aiLabel: 'warm',
    status: 'kontakt',
    lastContact: '2026-04-03',
    problem: 'Dużo no-show na wizytach, brak zautomatyzowanych przypomnień SMS',
    icebreaker: 'Gabinety dentystyczne z którymi pracuję redukują no-show o 60% – warto porozmawiać',
    website: 'dentica.pl',
    outreachHistory: [
      { date: '2026-04-03', type: 'LinkedIn DM', content: 'Pierwsze wyjście. Brak odpowiedzi.' },
    ],
  },
  {
    id: 'l4',
    firstName: 'Piotr',
    lastName: 'Lewandowski',
    company: 'ModaHouse',
    position: 'Head of Growth',
    email: 'piotr.l@modahouse.pl',
    phone: '+48 604 567 890',
    city: 'Gdańsk',
    segment: 'ecommerce',
    aiScore: 88,
    aiLabel: 'hot',
    status: 'pipeline',
    lastContact: '2026-04-07',
    problem: 'Wysoki CAC z Meta Ads, brak systemu do segmentacji leadów i retargetingu',
    icebreaker: 'ModaHouse wydaje dużo na reklamy – pokażę jak obniżyć CAC o 30% z AI scoringiem',
    website: 'modahouse.pl',
    outreachHistory: [
      { date: '2026-04-01', type: 'Cold DM', content: 'Wiadomość inicjalna.' },
      { date: '2026-04-04', type: 'Follow-up', content: 'Follow-up z case study e-commerce.' },
      { date: '2026-04-07', type: 'Rozmowa', content: 'Rozmowa 30 min – bardzo zainteresowany, czeka na ofertę.' },
    ],
  },
  {
    id: 'l5',
    firstName: 'Joanna',
    lastName: 'Szymańska',
    company: 'Restauracja Złota Rybka',
    position: 'Owner',
    email: 'joanna@zlotarybka.pl',
    phone: '+48 605 678 901',
    city: 'Poznań',
    segment: 'restauracje',
    aiScore: 62,
    aiLabel: 'warm',
    status: 'nowy',
    lastContact: '2026-04-02',
    problem: 'Brak systemu do zarządzania rezerwacjami online i zbierania opinii',
    icebreaker: 'Restauracje premium w Poznaniu które wdrożyły system zwiększyły obłożenie o 25%',
    website: 'zlotarybka.pl',
    outreachHistory: [
      { date: '2026-04-02', type: 'DM', content: 'Pierwsze wyjście – brak odpowiedzi.' },
    ],
  },
  {
    id: 'l6',
    firstName: 'Marek',
    lastName: 'Jabłoński',
    company: 'Suplementy Forte',
    position: 'Marketing Director',
    email: 'm.jablonski@suplementyforte.pl',
    phone: '+48 606 789 012',
    city: 'Łódź',
    segment: 'ecommerce',
    aiScore: 74,
    aiLabel: 'warm',
    status: 'kontakt',
    lastContact: '2026-04-04',
    problem: 'Niski ROAS na kampaniach Google, brak automatyzacji e-mail marketingu',
    icebreaker: 'Sklepy suplementów które obsługuję mają ROAS 4.5+ – mogę pokazać jak to osiągnęli',
    website: 'suplementyforte.pl',
    outreachHistory: [
      { date: '2026-04-01', type: 'LinkedIn', content: 'Zaproszenie.' },
      { date: '2026-04-04', type: 'DM', content: 'Wiadomość z ofertą. Czyta ale nie odpowiada.' },
    ],
  },
  {
    id: 'l7',
    firstName: 'Katarzyna',
    lastName: 'Wojciechowska',
    company: 'Kancelaria Wojciechowska & Partnerzy',
    position: 'Partner',
    email: 'k.wojciechowska@kancelaria-wp.pl',
    phone: '+48 607 890 123',
    city: 'Warszawa',
    segment: 'kancelarie',
    aiScore: 55,
    aiLabel: 'warm',
    status: 'nowy',
    lastContact: '2026-04-01',
    problem: 'Brak regularnej obecności w social media, trudno pozyskiwać klientów online',
    icebreaker: 'Kancelarie które prowadzę na LinkedIn mają 3x więcej zapytań w ciągu 6 miesięcy',
    website: 'kancelaria-wp.pl',
    outreachHistory: [
      { date: '2026-04-01', type: 'LinkedIn', content: 'Zaproszenie wysłane.' },
    ],
  },
  {
    id: 'l8',
    firstName: 'Tomasz',
    lastName: 'Kowalski',
    company: 'DevLoft Nieruchomości',
    position: 'CEO',
    email: 'tomasz@devloft.pl',
    phone: '+48 608 901 234',
    city: 'Kraków',
    segment: 'nieruchomości',
    aiScore: 81,
    aiLabel: 'hot',
    status: 'zainteresowany',
    lastContact: '2026-04-06',
    problem: 'Zbyt długi cykl sprzedaży, brak systemu do nurturingu leadów z portali',
    icebreaker: 'Deweloperzy z którymi pracuję skrócili cykl sprzedaży o 40% – pokażę case study',
    website: 'devloft.pl',
    outreachHistory: [
      { date: '2026-04-02', type: 'LinkedIn DM', content: 'Cold message.' },
      { date: '2026-04-06', type: 'DM #2', content: 'Follow-up z case study. Zainteresowany rozmową.' },
    ],
  },
  {
    id: 'l9',
    firstName: 'Agnieszka',
    lastName: 'Bąk',
    company: 'Beauty Academy Warsaw',
    position: 'Founder',
    email: 'agnieszka@beautyacademy.pl',
    phone: '+48 609 012 345',
    city: 'Warszawa',
    segment: 'beauty',
    aiScore: 93,
    aiLabel: 'hot',
    status: 'pipeline',
    lastContact: '2026-04-07',
    problem: 'Brak lejka sprzedażowego dla kursów online, leady z reklam giną',
    icebreaker: 'Twoje kursy beauty mają świetne opinie – teraz czas na system który zamieni ruch w sprzedaż',
    website: 'beautyacademy.pl',
    outreachHistory: [
      { date: '2026-03-25', type: 'LinkedIn', content: 'Zaproszenie + komentarz pod postem.' },
      { date: '2026-03-29', type: 'DM #1', content: 'Wstępna rozmowa.' },
      { date: '2026-04-03', type: 'Rozmowa', content: 'Demo systemu – super feedback.' },
      { date: '2026-04-07', type: 'Oferta', content: 'Oferta wysłana, czeka na decyzję.' },
    ],
  },
  {
    id: 'l10',
    firstName: 'Rafał',
    lastName: 'Kaczmarek',
    company: 'EduPro Szkolenia',
    position: 'CEO',
    email: 'rafal@edupro.pl',
    phone: '+48 610 123 456',
    city: 'Wrocław',
    segment: 'szkolenia',
    aiScore: 70,
    aiLabel: 'warm',
    status: 'kontakt',
    lastContact: '2026-04-04',
    problem: 'Mała frekwencja na szkoleniach online, brak automatycznych sekwencji mailingowych',
    icebreaker: 'Firmy szkoleniowe które wdrożyły sekwencje AI mają 2x wyższy fill rate kursów',
    website: 'edupro.pl',
    outreachHistory: [
      { date: '2026-04-04', type: 'LinkedIn', content: 'DM inicjalny. Odpowiedź: "Ciekawe, więcej info?"' },
    ],
  },
  {
    id: 'l11',
    firstName: 'Izabela',
    lastName: 'Nowak',
    company: 'Hotel Boutique Sopot',
    position: 'Owner',
    email: 'izabela@hotelsopot.pl',
    phone: '+48 611 234 567',
    city: 'Gdańsk',
    segment: 'hotele',
    aiScore: 67,
    aiLabel: 'warm',
    status: 'nowy',
    lastContact: '2026-04-03',
    problem: 'Za dużo rezerwacji przez OTA (booking.com), brak własnego kanału pozyskiwania',
    icebreaker: 'Hotele boutique które obsługuję zwiększyły bezpośrednie rezerwacje o 35% – warto porozmawiać',
    website: 'hotelsopot.pl',
    outreachHistory: [
      { date: '2026-04-03', type: 'LinkedIn', content: 'Zaproszenie wysłane.' },
    ],
  },
  {
    id: 'l12',
    firstName: 'Wojciech',
    lastName: 'Zielński',
    company: 'CrossFit Katowice',
    position: 'Owner',
    email: 'wojtek@crossfitkatowice.pl',
    phone: '+48 612 345 678',
    city: 'Katowice',
    segment: 'fitness',
    aiScore: 45,
    aiLabel: 'cold',
    status: 'nowy',
    lastContact: '2026-03-29',
    problem: 'Niski CR z próbnych treningów na płatne karnety',
    icebreaker: 'CrossFity które pracują z nami mają 70% CR z trialu na karnet – mogę pokazać jak',
    website: 'crossfitkatowice.pl',
    outreachHistory: [
      { date: '2026-03-29', type: 'DM', content: 'Brak odpowiedzi.' },
    ],
  },
  {
    id: 'l13',
    firstName: 'Magdalena',
    lastName: 'Pawlak',
    company: 'Klinika Estetyczna Perfekta',
    position: 'CEO',
    email: 'm.pawlak@perfekta.pl',
    phone: '+48 613 456 789',
    city: 'Warszawa',
    segment: 'medyczne',
    aiScore: 86,
    aiLabel: 'hot',
    status: 'zainteresowany',
    lastContact: '2026-04-05',
    problem: 'Brak CRM dla klientów klinicznych, follow-upy po zabiegach są ręczne',
    icebreaker: 'Kliniki estetyczne z automatycznym follow-upem mają 45% wyższy LTV klienta',
    website: 'perfekta.pl',
    outreachHistory: [
      { date: '2026-04-01', type: 'LinkedIn', content: 'Komentarz pod postem + zaproszenie.' },
      { date: '2026-04-05', type: 'DM', content: 'Rozmowa o problemach. Bardzo zainteresowana.' },
    ],
  },
  {
    id: 'l14',
    firstName: 'Bartosz',
    lastName: 'Wiśniewski',
    company: 'TechShop Online',
    position: 'Founder',
    email: 'bartosz@techshop.pl',
    phone: '+48 614 567 890',
    city: 'Poznań',
    segment: 'ecommerce',
    aiScore: 58,
    aiLabel: 'warm',
    status: 'kontakt',
    lastContact: '2026-04-02',
    problem: 'Wysoki cart abandonment rate, brak automatycznych sekwencji ratujących koszyk',
    icebreaker: 'E-sklepy które wdrożyły automatyzację cart recovery odzyskują 15-20% porzuconych koszyków',
    website: 'techshop.pl',
    outreachHistory: [
      { date: '2026-04-02', type: 'LinkedIn', content: 'DM inicjalny. Czyta.' },
    ],
  },
  {
    id: 'l15',
    firstName: 'Dorota',
    lastName: 'Mazurek',
    company: 'Yoga & Mindfulness Center',
    position: 'Owner',
    email: 'dorota@yogacenter.pl',
    phone: '+48 615 678 901',
    city: 'Kraków',
    segment: 'fitness',
    aiScore: 38,
    aiLabel: 'cold',
    status: 'nowy',
    lastContact: '2026-03-25',
    problem: 'Mała widoczność online, trudno pozyskiwać nowych uczestników zajęć',
    icebreaker: 'Centra wellbeing z którymi pracuję wypełniają grafik z 2 tygodniowym wyprzedzeniem',
    website: 'yogacenter.pl',
    outreachHistory: [
      { date: '2026-03-25', type: 'DM', content: 'Brak odpowiedzi.' },
    ],
  },
  {
    id: 'l16',
    firstName: 'Grzegorz',
    lastName: 'Adamski',
    company: 'Kancelaria Podatkowa Adamski',
    position: 'Partner',
    email: 'g.adamski@kancelaria-a.pl',
    phone: '+48 616 789 012',
    city: 'Gdańsk',
    segment: 'kancelarie',
    aiScore: 52,
    aiLabel: 'warm',
    status: 'nowy',
    lastContact: '2026-04-01',
    problem: 'Brak treści edukacyjnych w social media, zero pozyskiwania klientów online',
    icebreaker: 'Kancelarie podatkowe które prowadzą edukacyjny content na LinkedIn pozyskują 8-12 zapytań miesięcznie',
    website: 'kancelaria-a.pl',
    outreachHistory: [
      { date: '2026-04-01', type: 'LinkedIn', content: 'Zaproszenie.' },
    ],
  },
  {
    id: 'l17',
    firstName: 'Karolina',
    lastName: 'Michalak',
    company: 'FashionFirst',
    position: 'Head of Growth',
    email: 'karolina@fashionfirst.pl',
    phone: '+48 617 890 123',
    city: 'Łódź',
    segment: 'ecommerce',
    aiScore: 79,
    aiLabel: 'warm',
    status: 'zainteresowany',
    lastContact: '2026-04-06',
    problem: 'Brak personalizacji w e-mail marketingu, wszystkie maile idą do całej bazy',
    icebreaker: 'FashionFirst ma świetny produkt – brakuje tylko segmentacji która potroi konwersje z e-maili',
    website: 'fashionfirst.pl',
    outreachHistory: [
      { date: '2026-04-03', type: 'LinkedIn', content: 'Zaproszenie + wiadomość.' },
      { date: '2026-04-06', type: 'DM', content: 'Odpowiedziała pozytywnie, chce wiedzieć więcej.' },
    ],
  },
  {
    id: 'l18',
    firstName: 'Michał',
    lastName: 'Ostrowski',
    company: 'MedCenter Warszawa',
    position: 'CEO',
    email: 'm.ostrowski@medcenter.pl',
    phone: '+48 618 901 234',
    city: 'Warszawa',
    segment: 'medyczne',
    aiScore: 72,
    aiLabel: 'warm',
    status: 'kontakt',
    lastContact: '2026-04-05',
    problem: 'Długi czas oczekiwania na odpowiedź na zapytania online',
    icebreaker: 'Centra medyczne z automatyczną odpowiedzią na zapytania zwiększają booking rate o 50%',
    website: 'medcenter.pl',
    outreachHistory: [
      { date: '2026-04-05', type: 'LinkedIn DM', content: 'Wstępny kontakt. Czyta.' },
    ],
  },
  {
    id: 'l19',
    firstName: 'Natalia',
    lastName: 'Woźniak',
    company: 'Piekarnia Artisan',
    position: 'Owner',
    email: 'natalia@piekarnia-artisan.pl',
    phone: '+48 619 012 345',
    city: 'Wrocław',
    segment: 'restauracje',
    aiScore: 33,
    aiLabel: 'cold',
    status: 'nowy',
    lastContact: '2026-03-22',
    problem: 'Brak social media presence, klienci nie wiedzą o nowych produktach',
    icebreaker: '',
    website: 'piekarnia-artisan.pl',
    outreachHistory: [],
  },
  {
    id: 'l20',
    firstName: 'Łukasz',
    lastName: 'Grabowski',
    company: 'InnovateTech',
    position: 'CEO',
    email: 'lukasz@innovatetech.pl',
    phone: '+48 620 123 456',
    city: 'Katowice',
    segment: 'ecommerce',
    aiScore: 65,
    aiLabel: 'warm',
    status: 'nowy',
    lastContact: '2026-04-04',
    problem: 'Brak strategii content marketingowej, mała rozpoznawalność w branży',
    icebreaker: 'Firmy tech w Katowicach które prowadziłem na LinkedIn mają teraz 500+ inbound leads rocznie',
    website: 'innovatetech.pl',
    outreachHistory: [
      { date: '2026-04-04', type: 'LinkedIn', content: 'Zaproszenie wysłane.' },
    ],
  },
  {
    id: 'l21',
    firstName: 'Sylwia',
    lastName: 'Nowacka',
    company: 'Nails & Beauty Studio',
    position: 'Owner',
    email: 'sylwia@nailsbeauty.pl',
    phone: '+48 621 234 567',
    city: 'Warszawa',
    segment: 'beauty',
    aiScore: 76,
    aiLabel: 'warm',
    status: 'zainteresowany',
    lastContact: '2026-04-06',
    problem: 'Brak systemu rezerwacji online i przypomnień dla klientów',
    icebreaker: 'Studia beauty które wdrożyły system przypomnień redukują no-show o 70%',
    website: 'nailsbeauty.pl',
    outreachHistory: [
      { date: '2026-04-04', type: 'IG DM', content: 'Pierwsza wiadomość.' },
      { date: '2026-04-06', type: 'DM #2', content: 'Odpowiedziała – zainteresowana.' },
    ],
  },
  {
    id: 'l22',
    firstName: 'Paweł',
    lastName: 'Krupa',
    company: 'Akademia Biznesu Krupa',
    position: 'Founder',
    email: 'pawel@akademiabiznesu.pl',
    phone: '+48 622 345 678',
    city: 'Warszawa',
    segment: 'szkolenia',
    aiScore: 83,
    aiLabel: 'hot',
    status: 'pipeline',
    lastContact: '2026-04-07',
    problem: 'Skomplikowany proces sprzedaży kursów premium, brak automatyzacji onboardingu',
    icebreaker: 'Akademie biznesu z automatycznym onboardingiem mają 2x wyższy NPS i mniej rezygnacji',
    website: 'akademiabiznesu.pl',
    outreachHistory: [
      { date: '2026-03-28', type: 'LinkedIn', content: 'Komentarz pod postem o sprzedaży B2B.' },
      { date: '2026-04-02', type: 'DM', content: 'Rozmowa wstępna.' },
      { date: '2026-04-07', type: 'Rozmowa', content: 'Demo 45 min. Bardzo pozytywny feedback.' },
    ],
  },
  {
    id: 'l23',
    firstName: 'Elżbieta',
    lastName: 'Wróbel',
    company: 'Dom & Design Studio',
    position: 'Owner',
    email: 'ela@domdesign.pl',
    phone: '+48 623 456 789',
    city: 'Poznań',
    segment: 'nieruchomości',
    aiScore: 59,
    aiLabel: 'warm',
    status: 'nowy',
    lastContact: '2026-04-01',
    problem: 'Długi czas od zapytania do podpisania umowy, brak systemu do zarządzania projektami',
    icebreaker: '',
    website: 'domdesign.pl',
    outreachHistory: [
      { date: '2026-04-01', type: 'LinkedIn', content: 'Zaproszenie.' },
    ],
  },
  {
    id: 'l24',
    firstName: 'Robert',
    lastName: 'Kowalczewski',
    company: 'Prime Dental',
    position: 'CEO',
    email: 'robert@primedental.pl',
    phone: '+48 624 567 890',
    city: 'Gdańsk',
    segment: 'medyczne',
    aiScore: 71,
    aiLabel: 'warm',
    status: 'kontakt',
    lastContact: '2026-04-04',
    problem: 'Niska liczba rezerwacji online, większość pacjentów dzwoni – za dużo czasu recepcji',
    icebreaker: 'Gabinety które wdrożyły automatyczny booking online oszczędzają 3h recepcji dziennie',
    website: 'primedental.pl',
    outreachHistory: [
      { date: '2026-04-04', type: 'DM', content: 'Wstępna wiadomość. Czyta.' },
    ],
  },
  {
    id: 'l25',
    firstName: 'Monika',
    lastName: 'Zawadzka',
    company: 'Catering Premium Łódź',
    position: 'Owner',
    email: 'monika@cateringpremium.pl',
    phone: '+48 625 678 901',
    city: 'Łódź',
    segment: 'restauracje',
    aiScore: 48,
    aiLabel: 'cold',
    status: 'nowy',
    lastContact: '2026-03-28',
    problem: 'Brak systemu do zarządzania zamówieniami, wszystko na telefonach i w excelu',
    icebreaker: '',
    website: 'cateringpremium.pl',
    outreachHistory: [],
  },
]

export const SEGMENTS = ['beauty', 'fitness', 'medyczne', 'ecommerce', 'restauracje', 'kancelarie', 'nieruchomości', 'szkolenia', 'hotele']

export const SEGMENT_LABELS: Record<string, string> = {
  beauty: 'Beauty',
  fitness: 'Fitness',
  medyczne: 'Medyczne',
  ecommerce: 'E-commerce',
  restauracje: 'Restauracje',
  kancelarie: 'Kancelarie',
  nieruchomości: 'Nieruchomości',
  szkolenia: 'Szkolenia',
  hotele: 'Hotele',
}
